### ISSUE TITLE
'default' modifier propagates to abstract class 

### ISSUE THREAD

**Issue by yevhen13** [yevhen13/JFwdClassGen#10]
Input:

```
@Forwarding(style=FcStyle.ABSTRACT_CLASS)
public interface TestInterface {
  default void defaultMethodFromInterface() {
  }
}
```

Expected result:

```
public abstract class ForwardingTestInterface implements TestInterface {
  protected abstract TestInterface delegate();
  @Override
  public void defaultMethodFromInterface() {
    delegate().defaultMethodFromInterface();
  }
}
```

Actual result:

> Caused by: java.lang.IllegalStateException: CLASS ForwardingTestInterface .defaultMethodFromInterface cannot be default
>         at com.squareup.javapoet.Util.checkState(Util.java:71)
>         at com.squareup.javapoet.TypeSpec$Builder.addMethod(TypeSpec.java:504)

**Comment by yevhen13** [comment]
Method _com.squareup.javapoet.MethodSpec.overriding_ copies 'default' modifier & it seems impossible to remove this modifier afterwards.

**Comment by yevhen13** [comment]
For now, the best solution is to avoid using _com.squareup.javapoet.MethodSpec.overriding_.
Therefore, methods' overriding are to be done in more _manual_ manner.

**Comment by yevhen13** [comment]
Temporary fix.
